### PR TITLE
Change `LifeForm::MaxSpeed`

### PR DESCRIPTION
**Pull request by ooxi**
Old formula

```
max-speed_old(agility) = agility / 5
```

New formula

```
max-speed_new(agility, weight) = 1.5 * agility / (agility * weight + 7.5)
```

maxspeed

`max-speed_old` is blue, `max-speed_new` is red. x-axis is agility, y-axis is MaxSpeed. `weight` is fixed as one.

A `LifeForm`'s [initial agility is one](https://github.com/ooxi/violetland/blob/master/src/game/lifeforms/LifeForm.cpp#L13) and [increases slowly](https://github.com/ooxi/violetland/blob/master/src/windows/CharStatsWindow.cpp#L196).

### CODE REVIEW

**Comment by ooxi** [comment]
@bla-rs could you please describe the gameplay changes this commit achieves?

**Comment by bla-rs** [comment]
With the new speed, the gameplay only changes slightly because real high speeds are hard to reach / only later in the game.
None the less, i think this commit is very imporant because it allows ridiculous high agilities without the same effect on speed.
There should be a minimum possible speed, so aglity = 0 doenst mean speed = 0.

**Comment by ooxi** [comment]
Thanks for the explanation, I will merge this commit :+1: 

Since agility cannot decrease (as far as I know) and has an [initial value of one](https://github.com/ooxi/violetland/blob/master/src/game/lifeforms/LifeForm.cpp#L13) I don't think a situation could arise where `MaxSpeed` would be zero :)

**Comment by ooxi** [comment]
I have rebased and merged commit b8b532b099ebd6aed6d5b7b65136df814a9ee5c1 as d682711a0bad51f48805d3e84b0f8089b7ffd777 and verified the resulting binaries in [build #308](https://travis-ci.org/ooxi/violetland/builds/182519018).

Thanks for your contribution and sorry it took so long to integrate!

**Pull request closed without merging**
